# Generated by Django 4.2.7 on 2023-12-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_car'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
